DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS FRIENDSHIP CASCADE;
DROP TABLE IF EXISTS RATING CASCADE;
DROP TABLE IF EXISTS FILM CASCADE;
DROP TABLE IF EXISTS FILM_LIKE CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS FILM_GENRE CASCADE;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INTEGER NOT NULL AUTO_INCREMENT,
    EMAIL CHARACTER VARYING(50) NOT NULL,
    LOGIN CHARACTER VARYING(30) NOT NULL,
    NAME CHARACTER VARYING(30) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
    );

CREATE TABLE IF NOT EXISTS FRIENDSHIP (
    USER_FIRST_ID INTEGER NOT NULL,
    USER_SECOND_ID INTEGER NOT NULL,
    CONSTRAINT FRIENDSHIP_FK FOREIGN KEY (USER_FIRST_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FRIENDSHIP_FK_1 FOREIGN KEY (USER_SECOND_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS GENRE (
    GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
    GENRE_NAME CHARACTER VARYING(20) NOT NULL,
    CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID)
    );

CREATE TABLE IF NOT EXISTS RATING (
    RATING_ID INTEGER NOT NULL AUTO_INCREMENT,
    RATING_NAME CHARACTER VARYING(10) NOT NULL,
    CONSTRAINT RATING_PK PRIMARY KEY (RATING_ID)
    );

CREATE TABLE IF NOT EXISTS FILM (
    FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING(30) NOT NULL,
    DESCRIPTION CHARACTER VARYING(200) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL,
    RATING_ID INTEGER NOT NULL,
    CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID),
    CONSTRAINT FILM_FK FOREIGN KEY (RATING_ID) REFERENCES RATING(RATING_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS FILM_LIKE (
    FILM_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FILM_LIKE_PK PRIMARY KEY (USER_ID,FILM_ID),
    CONSTRAINT FILM_LIKE_FK FOREIGN KEY (FILM_ID) REFERENCES FILM(FILM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILM_LIKE_FK_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS FILM_GENRE (
    FILM_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID, GENRE_ID),
    CONSTRAINT FILM_GENRE_FK FOREIGN KEY (FILM_ID) REFERENCES FILM(FILM_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILM_GENRE_FK_1 FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
    );